// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3dqZ_ELeZiyHD8JYRjzSecS98g8gXac',
    appId: '1:630519322035:web:0f76e6707574939d2327c6',
    messagingSenderId: '630519322035',
    projectId: 'smartnutritrack',
    authDomain: 'smartnutritrack.firebaseapp.com',
    storageBucket: 'smartnutritrack.appspot.com',
    measurementId: 'G-5V8KCMQCF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5foy98EWeasJndDhE6HoqYqBbVq6KOM',
    appId: '1:630519322035:android:fb00794c31d9a1042327c6',
    messagingSenderId: '630519322035',
    projectId: 'smartnutritrack',
    storageBucket: 'smartnutritrack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvktfHfUpmuQoqpfqLMj1CHfrmETudmc',
    appId: '1:630519322035:ios:811f4bf388ebdb1a2327c6',
    messagingSenderId: '630519322035',
    projectId: 'smartnutritrack',
    storageBucket: 'smartnutritrack.appspot.com',
    iosClientId: '630519322035-1knn8cjlcb9h10fudctjude7jtiqvqcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartNutriTrack',
  );
}
